name: Subdomain Enumeration

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Target domain to scan'
        required: true
        default: 'siasindia.com'

jobs:
  enumerate-subdomains:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Add bin directory to PATH
        run: |
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          chmod -R +x $GITHUB_WORKSPACE/bin
      
      - name: Setup Python for subcat
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install subcat
        run: |
          pip install pipx
          pipx install subcat
          echo "$(pipx environment --value PIPX_BIN_DIR)" >> $GITHUB_PATH
      
      - name: Set target domain
        run: |
          echo "TARGET_DOMAIN=${{ github.event.inputs.domain }}" >> $GITHUB_ENV
      
      - name: Create output directory
        run: mkdir -p subdomain_results
      
      - name: Run subcat
        run: |
          subcat -silent -d ${{ env.TARGET_DOMAIN }} -o subdomain_results/subcat.txt || echo "Subcat failed"
    
      - name: Run Assetfinder
        run: |
          assetfinder --subs-only ${{ env.TARGET_DOMAIN }} | tee subdomain_results/assetfinder.txt || echo "Assetfinder failed"

      - name: Run Subfinder
        run: |
          subfinder -d ${{ env.TARGET_DOMAIN }} -all -recursive -t 200 -silent -o subdomain_results/subfinder-rescursive.txt || echo "Subfinder failed"
          
      - name: Run Findomain
        run: |
          findomain --quiet -t ${{ env.TARGET_DOMAIN }} | tee subdomain_results/findomain.txt || echo "Findomain failed"
    
      - name: Run GitHub Subdomains
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SUBDOMAIN_TOKEN }}
        run: |
          github-subdomains -d ${{ env.TARGET_DOMAIN }} -t $GITHUB_TOKEN -o subdomain_results/github.txt || echo "GitHub subdomains failed"
      
      - name: Combine and sort results
        run: |
          cd subdomain_results
          sort -u assetfinder.txt findomain.txt subcat.txt subfinder-rescursive.txt > passive.txt
          rm assetfinder.txt findomain.txt subcat.txt subfinder-rescursive.txt
          
          if [ -s passive.txt ] && [ -s github.txt ]; then
            grep -Fxvi -f passive.txt github.txt > unique_domains.txt || touch unique_domains.txt
          else
            touch unique_domains.txt
          fi
      
      - name: http probe unique
        run: |
          httpx -l subdomain_results/unique_domains.txt -title -sc -silent -no-color -location -p 80,443,8000,8080,8443 -td -cl -probe -o subdomain_results/httpx_output_unique.txt
          
      - name: http probe github
        run: |
          httpx -l subdomain_results/github.txt -title -sc -silent -no-color -location -p 80,443,8000,8080,8443 -td -cl -probe -o subdomain_results/httpx_output_github.txt
   
      - name: http probe passive
        run: |
          httpx -l subdomain_results/passive.txt -title -sc -silent -no-color -location -p 80,443,8000,8080,8443 -td -cl -probe -o subdomain_results/httpx_output_passive.txt
    
      - name: Upload results as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: subdomain-enum-results-${{ env.TARGET_DOMAIN }}-${{ github.run_id }}
          path: subdomain_results/
          retention-days: 7
      
      - name: Commit results
        run: |
          timestamp="2025-04-17 05:01:01"
          
          git config --global user.name "hexqubit"
          git config --global user.email "hexqubit@users.noreply.github.com"
          
          mkdir -p subdomains/${{ env.TARGET_DOMAIN }}
          cp -r subdomain_results/* subdomains/${{ env.TARGET_DOMAIN }}/
          
          git add subdomains/${{ env.TARGET_DOMAIN }}
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Subdomain enumeration results for ${{ env.TARGET_DOMAIN }} - $timestamp"
            git push
          fi

  screenshot-subdomains:
    needs: enumerate-subdomains
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Add bin directory to PATH
        run: |
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          chmod -R +x $GITHUB_WORKSPACE/bin
      
      - name: Set target domain and timestamp
        run: |
          echo "TARGET_DOMAIN=${{ github.event.inputs.domain }}" >> $GITHUB_ENV
          echo "TIMESTAMP=2025-04-17 05:01:01" >> $GITHUB_ENV
          echo "FILENAME_TIMESTAMP=20250417_050101" >> $GITHUB_ENV
      
      - name: Download subdomain results
        uses: actions/download-artifact@v4
        with:
          name: subdomain-enum-results-${{ env.TARGET_DOMAIN }}-${{ github.run_id }}
          path: subdomain_results
      
      - name: Install Chromium for screenshots
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser xvfb
      
      - name: Take screenshots - Unique Domains
        run: |
          if [ -f subdomain_results/httpx_output_unique.txt ]; then
            mkdir -p screenshots_unique
            cd screenshots_unique
            cat ../subdomain_results/httpx_output_unique.txt | grep -v "FAILED" | awk '{print $1}' > urls.txt
            xvfb-run --server-args="-screen 0 1280x1024x24" gowitness scan file -f urls.txt --threads 10 --screenshot-path ./screenshots --write-db --chrome-path /usr/bin/chromium-browser
            cd ..
          fi
      
      - name: Take screenshots - GitHub Domains
        run: |
          if [ -f subdomain_results/httpx_output_github.txt ]; then
            mkdir -p screenshots_github
            cd screenshots_github
            cat ../subdomain_results/httpx_output_github.txt | grep -v "FAILED" | awk '{print $1}' > urls.txt
            xvfb-run --server-args="-screen 0 1280x1024x24" gowitness scan file -f urls.txt --threads 10 --screenshot-path ./screenshots --write-db --chrome-path /usr/bin/chromium-browser
            cd ..
          fi
      
      - name: Take screenshots - Passive Domains
        run: |
          if [ -f subdomain_results/httpx_output_passive.txt ]; then
            mkdir -p screenshots_passive
            cd screenshots_passive
            cat ../subdomain_results/httpx_output_passive.txt | grep -v "FAILED" | awk '{print $1}' > urls.txt
            xvfb-run --server-args="-screen 0 1280x1024x24" gowitness scan file -f urls.txt --threads 10 --screenshot-path ./screenshots --write-db --chrome-path /usr/bin/chromium-browser
            cd ..
          fi
      
      - name: Compress screenshots with databases
        run: |
          if [ -d screenshots_unique ] && [ "$(ls -A screenshots_unique)" ]; then
            tar -czf screenshots_unique_${{ env.TARGET_DOMAIN }}_${{ env.FILENAME_TIMESTAMP }}.tar.gz screenshots_unique/
          fi
          
          if [ -d screenshots_github ] && [ "$(ls -A screenshots_github)" ]; then
            tar -czf screenshots_github_${{ env.TARGET_DOMAIN }}_${{ env.FILENAME_TIMESTAMP }}.tar.gz screenshots_github/
          fi
          
          if [ -d screenshots_passive ] && [ "$(ls -A screenshots_passive)" ]; then
            tar -czf screenshots_passive_${{ env.TARGET_DOMAIN }}_${{ env.FILENAME_TIMESTAMP }}.tar.gz screenshots_passive/
          fi
      
      - name: Upload screenshot results
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ env.TARGET_DOMAIN }}-${{ github.run_id }}
          path: screenshots_*.tar.gz
          retention-days: 7
